### ISSUE TITLE
Feature: Reorganize the functions and views of the app 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#114]
## Feature Description

Have a working user-friendly app. Change some existant view/features of the app such as: 

- Fix the buttons issues (have a different view according to the page (eg. Download, Favorites and Episodes page)). 
- Fix the Lock/Unlock reversed view on the Queue page. 
- Change some icons for them to be more appropriate for the function that they do. 
- Add the Search Bar in some appropriate pages.  
- Fix the issue in the menu bar of the # of subscription and # of episodes. 

## Feature Stories

- [x] As a user, I want to be able to have a working user-friendly app, so that I have an enjoyable user experience. #115

**Comment by ghost** [comment]
@guipadua Can you validate this feature? Thank you

**Comment by guipadua** [comment]
The description is too generic. Can you describe more specifically what you want to improve and maybe add mockups if you have?

**Comment by ghost** [comment]
@guipadua all the tasks are in the story #115, it's a few improvements in existing features of the app that do not really work properly. I have updated the feature description. 

I can mockup those but It would almost look the same but behave differently. Do you still want me to do mockups? 

Or would it be better to have a story for each task?

**Comment by guipadua** [comment]
I think the description is more specific now. It's important to know that so you are able to properly measure if the story is giving the wanted value.
