### ISSUE TITLE
Create burndown chart

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/390AntennaPod#12]
- [x] Select the points to do for sprint 1
- [x] Do planning poker for sprint 1
- [x] Create burndown chart for sprint 1

**Comment by ghost** [comment]
[Planning Poker - Sprint 1.pdf](https://github.com/FrankSauve/390AntennaPod/files/1671518/Planning.Poker.-.Sprint.1.pdf)

Here is the documentation for our Planning Poker and our Burndown chart for sprint 1.

**Comment by ghost** [comment]
I will redo the burndown chart according to when we closed the stories.
