### ISSUE TITLE
As a developer, I want to be able to build a class diagram

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/390AntennaPod#2]
- [x] Generate with a tool
- [x] Redo manually (Optional)

**Comment by ghost** [comment]
@jiggy357 generated the UML class diagram by using the software Visual Paradigm. 

![uml](https://user-images.githubusercontent.com/22198043/35486368-0737b3ee-043b-11e8-9fc8-02f43d1ab603.jpg)

**Comment by FrankSauve** [comment]
Currently redoing it in Cacoo

**Comment by ghost** [comment]
![35587555-2446cff0-05cc-11e8-8c1e-18dee1cccaa2](https://user-images.githubusercontent.com/22198043/35597901-896f9bb0-05ee-11e8-968d-06f0cafb6ce4.png)

Done by @LeCleric and @FrankSauve.

**Comment by guipadua** [comment]
Please try to add a more high-level view with some text that explains the architecture.

**Comment by ghost** [comment]
@jiggy357 how is it going with the class diagram ?

**Comment by ghost** [comment]
Link to view all the UML class diagrams done by Sarbeng Frimpong @jiggy357 : 
https://www.lucidchart.com/invitations/accept/a58d90a2-653c-42e8-8f11-12e96840bbfd
