### ISSUE TITLE
Feature: Trending tab

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#22]
## Feature Description

Have a trending tab in the user's menu. 

## Feature Stories

- [x] As a user, I want to be able to select the Trending tab in the side menu so that I can see trending podcasts. #28 

## Feature Mock-ups 

Original Menu GUI             |  New Menu GUI | New Trending page GUI
:-------------------------:|:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/13441191/35290362-0a2976d4-0038-11e8-9c32-f01c7085d12b.PNG" width="150"> | <img src="https://user-images.githubusercontent.com/13441191/35290430-3d871f04-0038-11e8-95c2-eabf65a0fea3.PNG" width="150"> | <img src="https://user-images.githubusercontent.com/13441191/35290403-21a9af36-0038-11e8-846c-517a43fc2553.PNG" width="150">

The mock-ups were done by @LeCleric.

**Comment by Raph1105** [comment]
# Feature Mock-ups

Original Menu GUI             |  New Menu GUI | New Trending page GUI
:-------------------------:|:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/13441191/35290362-0a2976d4-0038-11e8-9c32-f01c7085d12b.PNG" width="150"> | <img src="https://user-images.githubusercontent.com/13441191/35290430-3d871f04-0038-11e8-95c2-eabf65a0fea3.PNG" width="150"> | <img src="https://user-images.githubusercontent.com/13441191/35290403-21a9af36-0038-11e8-846c-517a43fc2553.PNG" width="150">

The mock-ups were done by @LeCleric .

**Comment by FrankSauve** [comment]
@guipadua

**Comment by guipadua** [comment]
Good to go. I'm assuming that trending here is just what itunes has as trending.
Maybe add stories for future with different options.
