### ISSUE TITLE
Feature: Discovery page

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#23]
## Feature Description

Have a preferences profile in the app. 
Have a discovery tab in the menu. 
Have a discovery page using the user's preferences.  

## Feature Stories

- [x]  As a user I want to be able to have my podcasts preferences stored, so that I can have a preferences profile in the app. #43 
- [x] As a user I want to be able to have a Discovery page so that I can have recommendations according to my preferences (entered in my preferences profile). #44

## Feature Mock-up

<img src="https://user-images.githubusercontent.com/13441191/35290584-a95e3a82-0038-11e8-90dc-58e5d0682947.PNG" width="150">
Mock-up done by @LeCleric. 

## Acceptance Testing
- Step 1: Navigate to the Settings page using the sidemenu 
- Step 2: Press the top option marked **Select your Categories Preferences**
- Step 3: Select which categories you are interested in from the pop-up which appears
- Step 4: Press the confirm button at the bottom right
- Step 5: Press the arrow pointing to the left besides the header marked **Settings**
- Step 6: Look through the displayed podcasts in order to ensure that all of them are from one of the categories you had selected
### [Video Showing Acceptance Tests](https://youtu.be/vu8tMdVDJjQ)
Video done by @LeCleric

**Comment by Raph1105** [comment]
@LeCleric could you create the mockups when you have time please ?
