### ISSUE TITLE
Create product backlog of features

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/390AntennaPod#3]
- [x] Study issues from https://github.com/AntennaPod/AntennaPod/issues
- [x] Pick feature we want to implement

**Comment by FrankSauve** [comment]
**Potential first feature**:

- #18 Ability to "Add to queue", "Mark as played", "Add to favorites" multiple podcasts via Downloads section https://github.com/AntennaPod/AntennaPod/issues/2508  

- ~~Option to delete episode after listening to it~~ (Already implemented)

- #22 Trending tab

- #23 A discovery tab for finding new podcasts

- Add a custom color scheme option for the GUI

**Comment by ghost** [comment]
Go to [Backlog Milestone](https://github.com/FrankSauve/390AntennaPod/milestone/4) to see all the features and stories in the product backlog.
