### ISSUE TITLE
Feature: Number of listens 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#31]
## Feature Description

Add in the number of listens for a podcast. 

## Feature Stories

- [ ] As a user, I want to be able to see the number of listens of a podcast, so that I can see if it is popular.

## Feature Mock-ups 

The mock-ups were done by .

**Comment by FrankSauve** [comment]
Itunes doesn't seem to return the number of listens.
See https://github.com/FrankSauve/390AntennaPod/wiki/Itunes-API-Reference
But maybe there is still a way
