### ISSUE TITLE
Feature: Reorganize the settings page 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#32]
## Feature Description

Make the settings page more user-friendly. 

## Feature Stories

- [x] As a user, I want to be able to have a user-friendly settings page, so that I can find what I am looking for quickly and easily.  #52

## Feature Mock-ups 
For the settings page, we intend to take the pre-existing sections in the settings page, and have selecting a section show all the toggles and options for that specific element, instead of displaying everything on one giant page as is currently the case. Implementing this feature will help with reducing the time users would have normally spent scrolling through the settings page.

Original Settings Page for AntennaPod             |  Mock-up for new Settings Page | Mock-up for Discovery Preferences Selection | Mock-up for User Interface Selection
:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/13441191/38001906-5b5122ea-31fd-11e8-8e2a-ce9b166762c6.jpg" height="500"> | <img src="https://user-images.githubusercontent.com/13441191/38003257-c065320a-3204-11e8-96ec-6c31312a7f59.PNG" width="150"> | <img src="https://user-images.githubusercontent.com/13441191/38003279-dc52b528-3204-11e8-839f-6cd0d3d00271.PNG" width="150"> | <img src="https://user-images.githubusercontent.com/13441191/38003270-d15ebe50-3204-11e8-875d-75661d8581c7.PNG" width="150">

The mock-ups were done by @LeCleric .

## Acceptance testing

[Click here to see the new, improved settings page](https://www.youtube.com/watch?v=RCAqYFX-0fI&feature=youtu.be) 
[Click here to see the old settings page](https://www.youtube.com/watch?v=xMeFjG_xws0&feature=youtu.be) 
Video done by @LeCleric

**Comment by ghost** [comment]
@LeCleric can you do the mock-up when you have time, please?

**Comment by LeCleric** [comment]
Alright, the mock-up is done.

**Comment by ghost** [comment]
@guipadua Can you please validate this feature? Thank you.
