### ISSUE TITLE
Feature: Parental Control

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#35]
## Feature Description

Have a parental control option in order to filter podcasts that have explicit content. 

## Feature Stories

- [ ] As a user, I want to be able to have a parental control option, so that podcasts with explicit content are filtered.

## Feature Mock-ups 

The mock-ups were done by .

**Comment by FrankSauve** [comment]
Itunes doesn't seem to return explicit tags
See https://github.com/FrankSauve/390AntennaPod/wiki/Itunes-API-Reference
But maybe we can just block the categories that look non child-friendly
