### ISSUE TITLE
Modify readme

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/390AntennaPod#5]
- [x] Add our names, id, team name.
- [x] Remove any useless info

**Comment by ghost** [comment]
Can I delete **FeedBack**, **Help Test AntennaPod**, **Nightly Builds** and **Translating AntennaPod** ? I find it not relevant to our project. 

<img width="922" alt="capture d ecran 2018-01-24 a 15 13 00" src="https://user-images.githubusercontent.com/22198043/35354766-2653bf68-0119-11e8-9e47-3092ab3be3f4.png">
<img width="752" alt="capture d ecran 2018-01-24 a 15 13 12" src="https://user-images.githubusercontent.com/22198043/35354767-2681e456-0119-11e8-9157-7e54dbb9fe5e.png">

**Comment by FrankSauve** [comment]
Yeah we don't need that
