### ISSUE TITLE
Story: Fix or delete non-working features

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#51]
## As a user, I want to be able to only see the working features, so that _(to complete)..._

- **Number of story points:** 5
- **Priority:** Low
- **Risk:**  Low to Medium
- _**Estimation of the ideal time**_: 5 hours

### Tasks TO DO: 

- [ ] task1

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write unit tests
- [ ] Write demo steps 
- [ ] Get TA signoff

**Comment by FrankSauve** [comment]
@Raph1105 Is this issue still relevant?
