### ISSUE TITLE
Story: CI

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/390AntennaPod#6]
## As a developer, I want to have a continuous integration set up, so that _(to complete)..._

- **Number of story points:** 5
- **Priority:** High
- **Risk:**  Medium
- _**Estimation of the ideal time**_ : 15 hours

### Tasks TO DO: 

- [x] Pick a CI tool
- [x] Setup CircleCI

### Test on a new PR for every team member
- [x] @FrankSauve #11 
- [x] @jiggy357  #13 
- [x] @LeCleric #14 
- [x] @williamkingbede #15 
- [x] @Raph1105 #16 
- [x] @Cotso 

### Dummy unit test 

**TO DO:  Create a unit test: "Dummy unit test" _(to see if CI runs this new unit test)_**
See dummytest branch
 
- [x] @FrankSauve 
- [x] @jiggy357  
- [x] @LeCleric 
- [x] @williamkingbede 
- [x] @Raph1105 
- [x] @Cotso

**Comment by FrankSauve** [comment]
We will use CircleCI because that is what the original project used

**Comment by FrankSauve** [comment]
Everything works! See PR #11

**Comment by FrankSauve** [comment]
My dummy test was picked up by circleCI and passed
https://59-116841114-gh.circle-artifacts.com/0/tmp/circle-junit.vy1a9gL/junit/de.test.antennapod.util.DummyTest.html

**Comment by FrankSauve** [comment]
We're only missing your dummy test @Cotso

**Comment by Raph1105** [comment]
#ebf0ce3
