### ISSUE TITLE
Feature: "Recommended for you" in the discovery tab

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/390AntennaPod#79]
## Feature Description

Load podcasts in the discovery tab based on what the user has previously listened.

## Feature Stories

- [x] As a user, I want to have a "Recommended for you" function in the preference page, so I can decide if I want to have automatic or manual suggestions. #81
- [x] As a user, I want to see suggested podcast based on what I have subscribed to previously. #90

## Feature Mock-ups 

<img src="https://user-images.githubusercontent.com/13441191/38003896-a7ad49f2-3207-11e8-9bfd-e1f4e220e730.png" width="150">

The mock-up was done by @LeCleric

## Acceptance Tests
[Click here to see the demo steps video.](https://youtu.be/fy0RVscoJbU) 
Descriptions of what is happening are in the video description.
Video done by @LeCleric

**Comment by ghost** [comment]
@LeCleric can you do the mock-up when you have time, please?

**Comment by LeCleric** [comment]
Made a mockup, might improve on it tomorrow

**Comment by ghost** [comment]
@guipadua Can you please validate this feature? Thank you.

**Comment by LeCleric** [comment]
Blue text were added in #107
Purple text were added in #116
In **_DiscoveryFragment_**: 
![image](https://user-images.githubusercontent.com/13441191/38773648-23d300aa-4020-11e8-97c2-c441f59699bd.png)
In **_ITunesSearchFragment_**:
![image](https://user-images.githubusercontent.com/13441191/38773662-6b099e0c-4020-11e8-941c-960c207030c8.png)
In **_antennapod.core.preferences.UserPreferences_**
![image](https://user-images.githubusercontent.com/13441191/38773676-a6035c28-4020-11e8-8ff4-7c2550fb2d91.png)
