### ISSUE TITLE
Story: Automatically share on Facebook 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/390AntennaPod#88]
## As a user, I want to be able to post automatically on Facebook whenever I listene to a podcast, so I can share it to my facebook friends.

- **Number of story points:** 5
- **Priority:** Low
- **Risk:**  Medium 
- _**Estimation of the ideal time**_ : 7 hours

### Tasks TO DO: 

- [ ] task1

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write unit tests
- [ ] Write demo steps 
- [ ] Get TA signoff

**Comment by LeCleric** [comment]
We're going to scope out this story and just keep twitter.

The reasons why are the following:
- Our gradle version is too outdated to use the current terminology that Facebook outlines in their docs (Our current version only understands the _compile_ keyword; it doesn't understand _implements_)
- When attempting to use an older version for implementing Facebook through dated resources showing how to add facebook functionality to an android project, other problems still persisted:
  - When registering the app, we received this message:
![image](https://user-images.githubusercontent.com/13441191/38695648-dffdb7ce-3e5a-11e8-828d-7b78a2853404.png)
  - When attempting to generate a Privacy Policy URL, the option to add posting privileges was behind a paywall.
<p align="center">
<img src = https://user-images.githubusercontent.com/13441191/38695830-690d5d9e-3e5b-11e8-887e-be411255097a.png width="500">
</p>
